name: Release and Version

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_version: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release Draft
        id: release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version-bump:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version in package.json
        run: |
          VERSION=${{ needs.release.outputs.release_version }}
          CLEAN_VERSION=${VERSION#v}
          npm version $CLEAN_VERSION --no-git-tag-version

      - name: Commit updated package.json
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: update package.json version to ${{ needs.release.outputs.release_version }}"
          git push
